### ISSUE TITLE
Examples should not have both JSON and YML

### ISSUE THREAD

**Issue by tschady** [finos-voice/voice-metadata-standard#7]
This will just cause duplication of effort.  
I suggest JSON only since that will increase adoption.

i.e. `ActiveStandard/callExample.json` and `ActiveStandard/callExample.yml`

**Comment by leop-tcto** [comment]
I would also rather only have one type. Yes the final version is JSON. YAML allows comments that will not appear in JSON by preceeding them with # which is the only reason YAML is here.

If we will be using JSON only then I think we only need to agree on how we will comment that JSON. For example is `"description":"my description"` field alone OK. Do we also need a `"comment":"my comment"` field?

Ideally I would like to be able to auto-generate documentation for JSON without that documentation being in the JSON itself. This is why I was thinking we start with YAML and the `#comments` would only appear in the auto-generated documentation. Oliver showed me an example from schema.org here: https://schema.org/Event. The vision is that from the YAML we generate JSON template to be filled in and at the same time we generate documentation like Schema.org.

I guess until we figure all this out we can just continue in  JSON for the time being since that may be less confusing. Thoughts?

**Comment by leop-tcto** [comment]
We agreed in the meeting on 2019-02-19 to abandon YAML. We will use JSON Schema to document the specification. Closing this issue as resolved.
